apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T19:03:26.7800591+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 3101d1e99231eba72d02a691e7bc26c1bfb211ebb28f0b81aeac6efe52b75784
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.12.tgz
    version: 2.1.12
generated: "2021-06-28T19:03:26.7789842+02:00"
