apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T17:53:27.9694303+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 08aca3ae64493d6a7074df2bd4c20b0e9c91cb7e486f6a7fc01464a692b44ad3
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.4.tgz
    version: 2.1.4
generated: "2021-06-28T17:53:27.9609404+02:00"
