apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T19:45:43.2706688+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 352f1f6d8bd81a2287d8cdeaf0ac6d3c8b8ed760cf3fb35aad93e26d6071baff
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.15.tgz
    version: 2.1.15
generated: "2021-06-28T19:45:43.2699811+02:00"
