apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T18:17:21.5415682+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 3cf525c470e52d797f0cf47f8bb23d67af8e500620809d67df7cf68d30df2d83
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.6.tgz
    version: 2.1.6
generated: "2021-06-28T18:17:21.540812+02:00"
