apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T19:42:36.0611763+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 112024f1981ffbd75b92c3d917da6c5601d7bbdb2166ec9876f8acd076504ae3
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.13.tgz
    version: 2.1.13
generated: "2021-06-28T19:42:36.0601799+02:00"
