apiVersion: v1
entries:
  aws-efs-csi-driver:
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2021-06-28T19:58:28.0082099+02:00"
    description: A Helm chart for AWS EFS CSI Driver
    digest: 404e09a48fa31c5a3d5f1f116c9737edc101d18fd7beb04a652ec6a90e8b1da0
    home: https://github.com/kubernetes-sigs/aws-efs-csi-driver
    keywords:
    - aws
    - efs
    - csi
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - name: leakingtapan
      url: https://github.com/leakingtapan
    - name: krmichel
      url: https://github.com/krmichel
    name: aws-efs-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/aws-efs-csi-driver
    urls:
    - aws-efs-csi-driver-2.1.16.tgz
    version: 2.1.16
generated: "2021-06-28T19:58:28.0074062+02:00"
